if: tag IS present
dist: xenial
language: python
python:
- '3.7'
install:
- pip install wheel
script: echo "No build-time tests to run."
deploy:
  provider: pypi
  user: adamrehn
  distributions: bdist_wheel
  on:
    tags: true
  password:
    secure: XP7pQB4OvEA0WZTA/TP9T0ia8XEnoWzpHy5mX2v5sXCvm/m5hLhRmY6g9fkPEF7/HVUYIVxUByjM172Ms9KwCMsNPvGrdnUakLpyVYljXd5Q1ESYsQInXouwHkrhQQKOQA0G+WV28e9jzntko9b9Vd91moRNG6cl6TZVwgp9oX6q2l5FGCEoN9Twi0mIxf34KHhuBQD4T/mqE8CcMPQliuAooEt275AzDOjyMUHrRF+MP4sVUfZwWF3q1ME/pTMKKE9wpH5p2VMVtRRQ7W7LFVCrvYOhrIzrqIYEM9vpSiCuSGwtcapXP9qBeZ3JQU6hXwgIv00MBK0SrBA2/NDdLw86PnJPc0WU3wnOfU1zh+8/TUloNXc0XRjUEYDeil7rYb7qYoJAITCLG7Y6/mplPyd2R+/AzVR2+iGyu0SAepbPiygTFsb5vQBp04/Y1Hy2lZ/equKLvoDZ0GDbu5/mnYFxGvyDIujDex+5mhD4alsVfyzYIY059We6wG8tuowqNwLL0fkJDmlzB3BhcAOPn+3jV0zDZpIdPRKgc6j50zrWHNmcJVVo/IaaICGSHkPPPaDp+YmWD/a27o7lVEE8dVUfX1EuS9mfigK7cC26vHxv/xCkjh6EDtzCTNlS9ZOxy3Zgg7ElvN1VLOyDsN4Msp07vyU+i2uj5j/qa42Y88A=
